### ISSUE TITLE
Scaling Behavior graph does not plot the Apple Dynamic Type behaviors as implied

### ISSUE THREAD

**Issue by thisisjeffwong** [Rightpoint/BonMot#339]
The scaling behaviors graph is missing `UIFontTextStyleLargeTitle` and `UIFontTextStyleTitle1` properties. Could these be added to the graph? The graph is very helpful.

![image](https://user-images.githubusercontent.com/1037533/40456160-cbeaed64-5ea4-11e8-807a-b148de132d15.png)

**Comment by ZevEisenberg** [comment]
We’re those styles added after iOS 9 or 10? That’s around when I created the graph. I think I may have the spreadsheet lying around, so if you can generate the values in question, I can add them and regenerate the graph. Thanks for pointing this out!
