### ISSUE TITLE
Link<a href> not working properly when enclosed within <h1> heading tag

### ISSUE THREAD

**Issue by harshitjain0803** [Rightpoint/BonMot#349]
Hi,

The below HTML text doesn't make 'Click Here' clickable while using BonMot for UITextView.
 
`"<h3>[<a href=\"https://google.com\">...Click Here</a>]</h3>"`

When I convert the HTML to string on UITextView without BonMot styling 'Click Here' works as link. But as I am using BonMot styling throughout the project and somehow this is not working.
Could you please help with the same.

![simulator screen shot - iphone se - 2018-10-23 at 16 10 08](https://user-images.githubusercontent.com/28865719/47355182-4c8a0e80-d6de-11e8-85d1-097237f501bb.png)

**Comment by ZevEisenberg** [comment]
Unfortunately, BonMot does not automatically convert `<a href=...` tags to links, since it is not a full HTML parser. I've considered adding it, but have run into various issues 😢
