### ISSUE TITLE
Migration from BonMot 3 to latest: pointTracking missing

### ISSUE THREAD

**Issue by DanielLeberle** [Rightpoint/BonMot#359]
Hi everyone,

I could not find it in the docs so I hope it's ok to ask the question here: BonMot 3 hat a "pointTracking" attribute, was that renamed? What is the new name?

Thanks in advance!
Daniel

**Comment by DanielLeberle** [comment]
sorry I found it!

**Comment by ZevEisenberg** [comment]
Glad you found it! For others looking: the new attribute is called `.tracking`, with `.point(CGFloat)` and `.adobe(CGFloat)` parameters available.
