### ISSUE TITLE
Xcode 13 featureIdentifier / typeIdentifier crash when deploying to earlier OS releases

### ISSUE THREAD

**Issue by chrisballinger** [Rightpoint/BonMot#415]
Seeing the following crash?

```
dyld: lazy symbol binding failed: Symbol not found: _$sSo26UIFontDescriptorFeatureKeya5UIKitE17featureIdentifierABvgZ
```

https://github.com/Rightpoint/BonMot/blob/924cda3adf40898d84c66e57447a8820e74516b4/Sources/Platform.swift#L30

<img width="525" alt="Screen Shot 2021-06-30 at 12 16 20 PM" src="https://user-images.githubusercontent.com/518687/124018741-044a4080-d99d-11eb-916d-d5cd48e0d028.png">

```
#12	0x000000010ffdabc1 in BONFontFeatureTypeIdentifierKey.unsafeMutableAddressor at Platform.swift:30
```

This is a known bug in Xcode 13 (`79090498`) that will hopefully be fixed by Apple soon. In the meantime you can't deploy code built with Xcode 13 to OS versions earlier than iOS 15.

> Apps that contain Swift code referencing featureIdentifier or typeIdentifier fail to launch on earlier OS releases. (79090498)

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes

If you find another workaround, please let us know!

**Comment by ZevEisenberg** [comment]
From Xcode 13 beta 4 release notes:
>Apps that contain Swift code referencing featureIdentifier or typeIdentifiernow launch in earlier OS releases. (79090498)
